site_name: napari-psf-simulator
site_description: A plugin for simulations of the Point Spread Function, with aberrations
site_author: Andrea Bassi

theme: readthedocs


repo_url: https://github.com/andreabassi78/napari-psf-simulator

pages:
- Home: index.md
