
# Add labels from the EDAM Bioimaging ontology
labels:
  ontology: EDAM-BIOIMAGING:alpha06
  terms:
  - Light microscopy
  - Fluorescence
  - Adaptive microscopy
  - Optical sectioning tomography
  - Image convolution
  - Instrument maintenance
 
